language: php

php: 7.3

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.composer/cache

install:
  - travis_retry composer update --no-interaction --no-suggest --prefer-dist --prefer-stable

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_script:
  - travis_retry wget https://scrutinizer-ci.com/ocular.phar
  - travis_retry php ocular.phar code-coverage:upload --format=php-clover coverage.xml